Update fai-cd-seedian for latest FAI.

diff --git a/bin/fai-cd-seedian b/bin/fai-cd-seedian
--- a/bin/fai-cd-seedian
+++ b/bin/fai-cd-seedian
@@ -5,7 +5,7 @@
 # fai-cd-seedian -- make a Seedian install CD that performs the FAI
 #
 # This script is a modified copy of fai-cd, which is part of FAI
-# (c) 2004-2016 by Thomas Lange, lange@informatik.uni-koeln.de
+# (c) 2004-2018 by Thomas Lange, lange@informatik.uni-koeln.de
 # Universitaet zu Koeln
 # Support for grub2 added by Sebastian Hetze, s.hetze@linux-ag.de
 # with major support from Michael Prokop, prokop@grml-solutions.com
@@ -38,6 +38,7 @@ set -e
 
 boot_image="boot/grub/eltorito.img"
 count=0
+space=0
 config_space=""
 configset=0
 forceremoval=0
@@ -62,7 +63,7 @@ hidedirs="/usr/share/locale /usr/share/doc /var/lib/apt /var/lib/aptitude /var/c
 usage() {
 
     cat <<-EOF
-	fai-cd Copyright (C) 2004-2016 Thomas Lange
+	fai-cd Copyright (C) 2004-2018 Thomas Lange
 
 	Usage: fai-cd [OPTIONS] -m MIRRORDIR ISONAME
 	Usage: fai-cd [OPTIONS] -B ISONAME
@@ -78,8 +79,31 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ERROR: $@" >&2   # print error message
+    echo -e "ERROR: $@" >&2   # print error message
     exit $e
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - -
+error_space() {
+
+    local e=$1
+    shift
+    local msg=$1
+    echo "Not enough space left on image for the $msg" >&2
+    df -h $tmp/$liveos/mounted-ext3fs >&2
+    echo "You can add more space to the image by using the option -s. See man fai-cd for details." >&2
+    die $e
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - -
+check_programs() {
+
+    local msg
+    [ $squash_only -eq 1 -o -x "$(which xorriso)" ] || msg+="xorriso not found. Please install package."
+    [ -x "$(which mksquashfs)" ] || msg+="\nmksquashfs not found. Please install the package squashfs-tools."
+    [ -x "$(which strings)" ] || msg+="\ncommand strings not found. Please install package binutils."
+
+    if [ -n "$msg" ]; then
+	die 8 "$msg"
+    fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
 create_ext3fs_image() {
@@ -88,29 +112,29 @@ create_ext3fs_image() {
     # along with it, a temporary folder is created to mount the ext3fs.img
     mkdir -p $tmp/$liveos/mounted-ext3fs
 
+    # hide some directories before copying the nfsroot
+    customize_nfsroot
     calculate_required_size
 
     # creates an empty file
     dd if=/dev/zero of=$tmp/$liveos/ext3fs.img bs=1MB count=$count 2>/dev/null ||
         die 9 "dd failed. Maybe no enough free space in $tmp"
 
-    mkfs.ext4 -q -O^has_journal -F -L FAI-NFSROOT $tmp/$liveos/ext3fs.img
+    mkfs.ext4 -m1 -q -O^has_journal -F -L FAI-NFSROOT $tmp/$liveos/ext3fs.img
 
     # the resulting ext3fs.img is mounted
     mount -o loop,noatime $tmp/$liveos/ext3fs.img $tmp/$liveos/mounted-ext3fs
 
-    # hide some directories before copying the nfsroot
-    customize_nfsroot
     echo "Copying the nfsroot to CD image"
     # copy the contents of the nfsroot into it
-    cp -Ppr $ONFSROOT/. $tmp/$liveos/mounted-ext3fs/ || die $? "Not enough space left on device for the nfsroot"
+    cp -Ppr $ONFSROOT/. $tmp/$liveos/mounted-ext3fs/ || error_space $? "nfsroot"
     rm -f $tmp/$liveos/mounted-ext3fs/etc/resolv.conf
 
     # find $tmp/$liveos/mounted-ext3fs # for debugging
     # copy config space into nfsroot-copy unless -d is given
     if [ $configset -eq 0 ]; then
         echo "Copying the config space to CD image"
-        cp -Ppr $FAI_CONFIGDIR/* $tmp/$liveos/mounted-ext3fs/var/lib/fai/config/ || die $? "Not enough space left on device for the config directory"
+        cp -Ppr $FAI_CONFIGDIR/* $tmp/$liveos/mounted-ext3fs/var/lib/fai/config/ || error_space $? "config directory"
     fi
     # add the partial mirror to the CD
     addmirror
@@ -196,40 +220,20 @@ create_grub2_image() {
 
     mkdir -p $tmp/boot/grub $NFSROOT/boot/grub
     if [ -f $NFSROOT/boot/grub/core.img ]; then
-        cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
-        MODULEBASE=$NFSROOT/usr/lib/grub
+        :
     elif [ -f $NFSROOT/usr/lib/grub/i386-pc/cdboot.img ]; then
-        chroot $NFSROOT /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660 --format=i386-pc
-        cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
-        MODULEBASE=$NFSROOT/usr/lib/grub
+        chroot $NFSROOT /usr/bin/grub-mkimage -p /boot/grub -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660 --format=i386-pc
     else
-        echo "no grub2 installation found in NFSROOT, using downloaded $grubPackage"
-        apt-get -y -d install --reinstall grub-pc >/dev/null
-        grubPackage=`ls -rt /var/cache/apt/archives/grub-pc*|tail -1`
-        if [ -z "$grubPackage" ]; then
-            die 22 "Downloading grub2 failed."
-        fi
-        GRUBDIR=$tmp/grubPackage
-        mkdir -p $GRUBDIR
-        dpkg -x $grubPackage $GRUBDIR
-        cd $GRUBDIR
-        ./usr/bin/grub-mkimage -d usr/lib/grub/*-pc -o $tmp/boot/grub/core.img biosdisk iso9660 --format=i386-pc
-        MODULEBASE=$GRUBDIR/usr/lib/grub
+        die 11 "No grub-pc installation found in NFSROOT. Aborting."
     fi
+    cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
+    cp $NFSROOT/boot/grub/unicode.pf2 $tmp/boot/grub
 
-    # check for jessie path
-    if strings $NFSROOT/usr/lib/grub/i386-pc/kernel.img | grep -q i386-pc/%s.mod; then
-	grubtarget=$tmp/boot/grub/i386-pc
-    else
-	# wheezy
-	grubtarget=$tmp/boot/grub
-    fi
-
+    grubtarget=$tmp/boot/grub/i386-pc
     mkdir -p $grubtarget
-    for a in $MODULEBASE/*-pc/{*.mod,efiemu??.o,cdboot.img,boot.img,command.lst,moddep.lst,fs.lst,handler.lst,parttool.lst}; do
+    for a in $NFSROOT/usr/lib/grub/*-pc/{*.mod,efiemu??.o,cdboot.img,boot.img,command.lst,moddep.lst,fs.lst,handler.lst,parttool.lst}; do
         [[ -e $a ]] && cp $a $grubtarget
     done
-    rm -rf $GRUBDIR
     cp $grub_config $tmp/boot/grub/grub.cfg
     # insert date into grub menu
     perl -pi -e "s/_VERSIONSTRING_/   $isoversion     /" $tmp/boot/grub/grub.cfg
@@ -257,7 +261,8 @@ calculate_required_size() {
     fi
 
     # not dividing by 1024 to get the exact, this allows us to get some additional space
-    count=$(($size/900))
+    # add some addition space
+    count=$(($size/850 + $space))
 }
 
 provide_memtest_boot_option() {
@@ -268,11 +273,9 @@ provide_memtest_boot_option() {
 
     if [ -f $NFSROOT/boot/memtest86+.bin ]; then
         cp $NFSROOT/boot/memtest86+.bin $tmp/boot
-    elif [ -f /boot/memtest86+.bin ]; then
-        cp /boot/memtest86+.bin $tmp/boot
+        echo "Adding memtest86+ to grub menu"
     else
-        echo "no memtest86+.bin found, omit memtest boot option"
-        return
+        return 0
     fi
 
     cat >> $tmp/boot/grub/grub.cfg <<EOF
@@ -321,7 +324,7 @@ unhide_dirs() {
 		umount  $target/$d 2>/dev/null
             fi
 	else
-            if [ -d $nfsrootdir/$d ]; then
+            if [ -d $ONFSROOT/$d ]; then
 		[ "$debug" ] && echo "disclosing $d"
 		umount $ONFSROOT/$d 2>/dev/null
             fi
@@ -336,14 +339,17 @@ cleanup_liveos_mounts() {
     unhide_dirs
     rm -rf $tmp
     if [ $autodiscover -eq 1 -o $xenserver_support -eq 1 ]; then
-	mv $ONFSROOT/tmp/initrd.img* $ONFSROOT/boot 2>/dev/null
+        local initrdfiles=($ONFSROOT/tmp/initrd.img*)
+        if [[ -e $initrdfiles ]]; then
+	    mv "${initrdfiles[@]}" $ONFSROOT/boot 2>/dev/null
+        fi
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
 mkiso() {
 
     echo "Writing FAI CD-ROM image to $isoname. This may need some time."
-    xorriso -report_about HINT -as mkisofs -graft-points -b $boot_image \
+    xorriso -report_about HINT -as mkisofs -iso-level 3 -graft-points -b $boot_image \
         -V "$vname" -A "$aname" \
         -no-emul-boot -boot-info-table --embedded-boot ${embed_image} -partition_offset 16 -no-pad -o $isoname \
         -R $tmp --sort-weight 0 / --sort-weight 1 /boot || die 12 "xorriso failed."
@@ -358,8 +364,8 @@ addmirror() {
 
     mkdir $tmp/$liveos/mounted-ext3fs/media/mirror
 
-    echo "Copying mirror to CD image"
-    cp -Pr $mirrordir/{dists,pool} $tmp/$liveos/mounted-ext3fs/media/mirror 2>/dev/null || die $? "Not enough space left on device for the mirror"
+    echo "Copying the mirror to CD image"
+    cp -Pr $mirrordir/{dists,pool} $tmp/$liveos/mounted-ext3fs/media/mirror 2>/dev/null || error_space $? "mirror"
 
     # create the sources.list for the CD
     cat > $tmp/$liveos/mounted-ext3fs/etc/apt/sources.list <<EOF
@@ -373,7 +379,7 @@ EOF
     for i in $dists ; do
         comp=$(find $mirrordir/dists/$i -maxdepth 2 -type d -name "binary-*" | \
         sed -e "s#$mirrordir/*dists/$i/##" -e 's#/binary-.*##' | uniq | tr '\n' " ")
-        echo "deb file:/media/mirror $i $comp" >> $tmp/squashfs-root/LiveOS/mounted-ext3fs/etc/apt/sources.list
+        echo "deb [trusted=yes] file:/media/mirror $i $comp" >> $tmp/squashfs-root/LiveOS/mounted-ext3fs/etc/apt/sources.list
     done
 
 }
@@ -386,9 +392,10 @@ burniso() {
 # main program
 
 # Parse commandline options
-while getopts "AenkfhHg:JbSBMm:C:d:X" opt ; do
+while getopts "AekfhHg:Jbs:SBMn:m:c:C:d:X" opt ; do
     case "$opt" in
 	A)  autodiscover=1 ;;
+        c)  csdir="$OPTARG" ;;
         C)  cdir="$OPTARG" ; arguments+=" -C $cdir";;
         e)  hidevartmp=1 ;;
         f)  forceremoval=1 ;;
@@ -398,7 +405,9 @@ while getopts "AenkfhHg:JbSBMm:C:d:X" opt ; do
         J)  sqopt="-comp xz" ; arguments+=" -J";;
         M)  nomirror=1 ;;
         m)  mirrordir="$OPTARG" ;;
+        n)  setnfsroot="$OPTARG" ;;
         b)  burn=1 ; arguments+=" -b";;
+        s)  space="$OPTARG" ;;
         S)  squash_only=1 ;;
         B)  bootonly=1 ;;
         d)  config_space="$OPTARG"; configset=1 ; arguments+=" -d $config_space";;
@@ -414,10 +423,15 @@ if [ $autodiscover -eq 1 ]; then
     nomirror=1
     bootonly=1
     hidedirs="
-    net/ceph
-    net/wireless
     sound
+    net/ceph
+    fs/ceph
+    fs/ocfs2
+    fs/btrfs
+    fs/xfs
+    drivers/net/wireless
     drivers/block/drbd
+    drivers/hwmon
     drivers/staging/lustre
     drivers/scsi
     drivers/ata
@@ -447,9 +461,7 @@ if [ $bootonly -eq 0 ]; then
     [ $(id -u) != "0" ]   && die 9 "Run this program as root."
 fi
 
-[ $squash_only -eq 1 -o -x "$(which xorriso)" ] || die 8 "xorriso not found. Please install package."
-[ -x "$(which mksquashfs)" ] || die 8 "mksquashfs not found. Please install the package squashfs-tools."
-[ -x "$(which strings)" ] || die 8 "command strings not found. Please install package binutils."
+check_programs
 
 # use FAI_ETC_DIR from environment variable
 if [ -n "$FAI_ETC_DIR" -a -z "$cdir" ]; then
@@ -463,10 +475,17 @@ if [ ! -d "$cfdir" ]; then
     echo "$cfdir is not a directory" >&2
     exit 6
 fi
-[ "$verbose" ] && echo "Using configuration files from $cfdir"
+[ X$verbose = X1 ] && echo "Using configuration files from $cfdir"
 . $cfdir/fai.conf
 . $cfdir/nfsroot.conf
 : ${FAI:=/var/lib/fai/config} # default value
+
+if [ -n "$setnfsroot" ]; then
+   NFSROOT=$setnfsroot # override by -n
+fi
+if [ -n "$csdir" ]; then
+    FAI_CONFIGDIR=$csdir # override by -c
+fi
 ONFSROOT=$NFSROOT # save original nfsroot
 
 if [ $autodiscover -eq 1 ]; then
@@ -491,7 +510,7 @@ echo $grub_config | grep -q '/' || grub_config="$cfdir/$grub_config"
 [ -f "$grub_config" ] || die 13 "Grub menu file $grub_config not found."
 
 if [ $bootonly -eq 0 -o $configset -eq 1 ]; then
-    [ -z "$FAI_CONFIGDIR" ]  && die 14 "Variable \$FAI_CONFIG not set."
+    [ -z "$FAI_CONFIGDIR" ]  && die 14 "Variable \$FAI_CONFIGDIR not set."
     [ -d $FAI_CONFIGDIR ] || die 15 "Can't find config space $FAI_CONFIGDIR."
     [ -d $FAI_CONFIGDIR/class ] || die 16 "Config space $FAI_CONFIGDIR seems to be empty."
 fi
